version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: thisismysupersecrettext
        databases:
          default:
            connector: postgres
            host: ec2-35-172-73-125.compute-1.amazonaws.com
            database: d8mc4mcp94s020
            schema: public
            user: ihncudenshlhbk
            password: b68d3255083d4282b5d2ae3f07c9c3963ea0ee130f6150ccab6ca87a3274b38b
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true