apiVersion: apps/v1
kind: Deployment
metadata:
    name: red
    labels:
        app: sample
spec:
    template:
        metadata:
            name: red
            labels:
                app: sample
        spec:
            containers:
                - name: nginx
                  image: nginx
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: node-role.kubernetes.io/master
                                  operator: "Exists"
    replicas: 3
    selector:
        matchLabels:
            app: sample