apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod 
spec:
    containers:
        - name: nginx-containers
          iamge: nginx
    tolerations:
        - key: app
          operator: "Equal"
          value: "blue"
          effect: "NoSchedule"