# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180918_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
