# Generated by Django 2.0.1 on 2018-01-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_quiz_times_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='published',
            new_name='is_live',
        ),
    ]
